# Dependencies
markdown: redcarpet
pygments: true

# Permalinks
permalink: pretty

# Setup
title: Current
tagline: 'Design e Desenvolvimento Web'
description: 'Desde 2009 criando aplicações web.'
url: http://www.current.com.br

author:
  name: 'Rafael Masoni'
  url: http://rafaelmasoni.com/

paginate: 1

# Custom vars
version: 1.0.0

github:
  repo: https://github.com/oicurrent/oicurrent.github.com
